/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:64ecce4e-3d8a-4570-88e1-1ee6996e3663",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_K8tZbCnXc",
    "aws_user_pools_web_client_id": "43q271i09ld4kgdtf2be6i7k2e",
    "oauth": {
        "domain": "trelloclone4746a536-4746a536-dev.auth.ap-southeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://trello-clone-dun.vercel.app/",
        "redirectSignOut": "http://localhost:3000/,https://trello-clone-dun.vercel.app/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://wbndrnx4p5extd6vhanm3ch3ou.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
